version: '3.8'

services:
  web:
    build:
      context: ./back/app
      dockerfile: Dockerfile.prod
    command: gunicorn crescent.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./back/.env.prod
    depends_on:
      - db

  front:
    container_name: front
    restart: always
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - 8080:8080
    expose:
      - 8080

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./back/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
