version: '3.9'

services:
  back:
    container_name: back
    restart: always
    build:
      context: .
      dockerfile: ./compose/back/Dockerfile
    volumes:
      - ./back:/back
    ports:
      - 7000:7000
    expose:
      - 7000

  front:
    container_name: front
    restart: always
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - front
