# Generated by Django 4.2.3 on 2023-10-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0004_rename_news_newsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='summary',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
