# Generated by Django 4.2.3 on 2023-10-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0006_newsmodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
