# Generated by Django 4.2.3 on 2023-10-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0008_productcardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcardmodel',
            name='category',
            field=models.CharField(choices=[('モーションキャプチャー', 'MOTION_CAPTURE'), ('ボリュメトリックキャプチャー', 'VOLUMETRICS_CAPTURE'), ('フォトグラフメトリ', 'PHOTOGRAMMETRY'), ('Coming soon', 'COMING_SOON')], default='モーションキャプチャー', max_length=20),
        ),
    ]
