# Generated by Django 4.2.3 on 2023-11-13 02:42

import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0009_alter_productcardmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(default='images/Placeholder.png', upload_to=crescentSite.models.ServicesModel.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productcardmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
