# Generated by Django 4.2.3 on 2023-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
