# Generated by Django 4.2.3 on 2023-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0002_yourmodel_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='cover',
            field=models.ImageField(default='images/Placeholder.png', upload_to='images/'),
        ),
    ]
