# Generated by Django 4.2.3 on 2023-10-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0003_news_alter_yourmodel_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
