# Generated by Django 4.2.3 on 2023-10-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0005_remove_newsmodel_summary_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
