# Generated by Django 4.2.3 on 2023-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0010_servicesmodel_alter_newsmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='category',
            field=models.CharField(choices=[('イベント', 'EVENT'), ('製品情報', 'PRODUCT_INFO'), ('その他', 'OTHER')], default='イベント', max_length=20),
        ),
    ]
