# Generated by Django 4.2.3 on 2023-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0012_viconproduct_alter_newsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='viconproduct',
            name='category',
            field=models.CharField(choices=[('CAMERA', 'CAMERA'), ('SOFTWARE', 'SOFTWARE'), ('HARDWARE', 'HARDWARE')], default='CAMERA', max_length=20),
        ),
    ]
