# Generated by Django 4.2.3 on 2023-11-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0013_remove_image_title_alter_viconproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viconproduct',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='viconproduct',
            name='images',
        ),
        migrations.AlterField(
            model_name='content',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='crescentSite.viconproduct'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crescentSite.viconproduct'),
        ),
    ]
