# Generated by Django 4.2.3 on 2023-11-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0014_remove_viconproduct_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MOTION_CAPTURE', 'モーションキャプチャー'), ('VOLUMETRICS_CAPTURE', 'ボリュメトリックキャプチャー'), ('PHOTOGRAMMETRY', 'フォトグラフメトリ'), ('CAMERA', 'CAMERA'), ('SOFTWARE', 'SOFTWARE'), ('HARDWARE', 'HARDWARE'), ('COMING_SOON', 'Coming soon')], default='CAMERA', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='ProductCardModel',
        ),
        migrations.AlterField(
            model_name='content',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='crescentSite.product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crescentSite.product'),
        ),
        migrations.DeleteModel(
            name='ViconProduct',
        ),
    ]
