# Generated by Django 4.2.3 on 2023-11-28 07:20

import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0015_product_delete_productcardmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='images/Placeholder.png', upload_to=crescentSite.models.Product.upload_to),
        ),
    ]
