# Generated by Django 4.2.3 on 2023-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0016_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sorting_order',
            field=models.IntegerField(default=0),
        ),
    ]
