# Generated by Django 4.2.3 on 2023-12-08 01:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0019_testcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcontent',
            name='testcontent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
