# Generated by Django 4.2.3 on 2023-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0020_alter_testcontent_testcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sorting_order'], 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='testcontent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='testcontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
