# Generated by Django 4.2.3 on 2023-12-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0021_alter_product_options_alter_testcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcontent',
            options={},
        ),
    ]
