# Generated by Django 4.2.3 on 2023-12-08 02:08

import ckeditor.fields
import crescentSite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0022_alter_testcontent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=100)),
                ('productImage', models.ImageField(upload_to=crescentSite.models.ProductContent.upload_to)),
                ('productText', ckeditor.fields.RichTextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productContent', to='crescentSite.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Testcontent',
        ),
    ]
