# Generated by Django 4.2.3 on 2023-12-08 02:14

import ckeditor.fields
import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0023_productcontent_delete_testcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='productImage',
            field=models.ImageField(upload_to=crescentSite.models.ProductContent.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='productText',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='productTitle',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
