# Generated by Django 4.2.3 on 2023-12-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0024_alter_productcontent_productimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontent',
            options={'verbose_name_plural': 'Product Content'},
        ),
    ]
