# Generated by Django 4.2.3 on 2023-12-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0025_alter_productcontent_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcontent',
            old_name='productImage',
            new_name='image',
        ),
    ]
