# Generated by Django 4.2.3 on 2023-12-08 04:04

import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0026_rename_productimage_productcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='image',
            field=models.ImageField(blank=True, upload_to=crescentSite.models.ProductContent.upload_to, verbose_name='Image'),
        ),
    ]
