# Generated by Django 4.2.3 on 2023-12-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0027_alter_productcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='productTitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
