# Generated by Django 4.2.3 on 2023-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0028_alter_productcontent_producttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='section',
            field=models.CharField(choices=[('OVERVIEW', '概要'), ('USAGE', '用途'), ('DETAILS_PRICE', '詳細・金額'), ('CATALOG_DOWNLOAD', 'カタログダウンロード'), ('OTHER', 'その他')], default='概要', max_length=20),
        ),
    ]
