# Generated by Django 4.2.3 on 2023-12-08 05:48

import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0029_productcontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='hero',
            field=models.ImageField(default='images/Placeholder.png', upload_to=crescentSite.models.Product.upload_to),
        ),
    ]
