# Generated by Django 4.2.3 on 2023-12-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0030_product_description_product_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
