# Generated by Django 4.2.3 on 2023-12-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0031_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
