# Generated by Django 4.2.3 on 2023-12-12 07:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0032_remove_image_product_delete_content_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SOLUTION', 'ソリューション'), ('SOFTWARE', 'ソフトウェア'), ('DEVICE', 'デバイス')], default='CAMERA', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='productText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='section',
            field=models.CharField(choices=[('OVERVIEW', '概要'), ('FEATURE', '特徴'), ('DETAILS_PRICE', '仕様・価格'), ('SUPPORT', 'サポート'), ('OTHER', 'その他')], default='概要', max_length=20),
        ),
    ]
