# Generated by Django 4.2.3 on 2023-12-14 09:34

import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0034_usercase_alter_newsmodel_content_delete_newsimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercase',
            name='thumbnail',
            field=models.ImageField(default='images/Placeholder.png', upload_to=crescentSite.models.Usercase.upload_to),
        ),
    ]
