# Generated by Django 4.2.3 on 2023-12-15 04:07

import ckeditor_uploader.fields
import crescentSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crescentSite', '0035_usercase_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(default='images/Placeholder.png', upload_to=crescentSite.models.Special.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Special Feature',
            },
        ),
        migrations.AlterModelOptions(
            name='usercase',
            options={'verbose_name_plural': 'Usercase'},
        ),
        migrations.RemoveField(
            model_name='usercase',
            name='sorting_order',
        ),
    ]
